global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - 'alert-rule-camel.yml'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'

    scrape_interval: 5s

    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080

  - job_name: 'node-exporter'

    scrape_interval: 5s

    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100

  - job_name: 'camel-microservice-demo'

    static_configs:
      - targets:
          - 'name-client-service:9779'
          - 'name-prefix-service:9779'
          - 'name-suffix-service:9779'