metadata:
  name: "name-suffix-service"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8082
    name: http
  - port: 9779
    protocol: "TCP"
    targetPort: 9779
    name: prometheus
  type: "NodePort"