metadata:
  labels:
    hystrix.enabled: "true"
spec:
  selector:
    matchLabels:
      hystrix.enabled: "true"
  template:
    metadata:
      labels:
        hystrix.enabled: "true"
    spec:
      serviceAccountName: "camel-microservice-demo"
      containers:
      - env:
        - name: "AB_OFF"
          value: "true"
        - name: "JAVA_OPTIONS"
          value: "-Djava.net.preferIPv4Stack=true"
        - name: "JAEGER_SERVICE_NAME"
          value: "camel-microservice-demo"
        - name: "JAEGER_REPORTER_LOG_SPANS"
          value: "false"
        - name: "JAEGER_SAMPLER_TYPE"
          value: "const"
        - name: "JAEGER_SAMPLER_PARAM"
          value: "1"
        - name: "JAEGER_AGENT_HOST"
          value: "opentracing"
        - name: "JAEGER_AGENT_PORT"
          value: "6831"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180