metadata:
  labels:
  name: "name-prefix-service"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8081
    name: http
  - port: 9779
    protocol: "TCP"
    targetPort: 9779
    name: prometheus
  type: "NodePort"